server:
  port: 9091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todoappdev?useSLL=false&serverTimezone=UTC&useLegacyDateTimeCode=false
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

management:
  endpoints:
    web:
      exposure:
        include: refresh

      