spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todoapp?useSLL=false&serverTimezone=UTC&useLegacyDateTimeCode=false
    username: root
    password:

#Show sql queries
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect